### ISSUE TITLE
Add index.yml

### ISSUE THREAD

**Issue by adamhgriffith-uofu** [chpc-uofu/OOD-pe-apps-v3#1]
To aid in automation, create an `index.yml` file using the following structure:
```yaml
apiVersion: v1
entries:
  appname: []
  anotherappname: []
```
The empty arrays leave room for possible future attribution.

This relates to https://github.com/chpc-uofu/OOD-apps-v3/issues/3.
